# rename/copy to database.yml and adjust to your local settings

base: &base
  adapter: sqlserver
  host: 192.168.99.100
  port: 50012
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: dummy

development:
  <<: *base

test:
  <<: *base
